project:
  type: website
  output-dir: docs
  title: Rafi Mikail
website:
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: posts.qmd
        text: Posts
  search: false
format:
  html:
    theme: litera
    css: styles.css
    toc: false
execute:
  freeze: auto